repos:
  - repo: local
    hooks:
      - id: commit-msg-check
        name: Commit msg check
        entry: ./scripts/commit-msg-hook.sh
        language: script
        stages: [commit-msg]
